[workspace]
members = [
    "boxlocker",
    "fxa-rust-client",
    "fxa-rust-client/ffi",
    "sync15-adapter",
    "sync15-adapter/ffi",
    "sync-pw-sql-store"
]

# For RSA keys cloning. Remove once openssl 0.10.8+ is released.
[patch.crates-io]
openssl = { git = 'https://github.com/sfackler/rust-openssl', rev = '5debc1ba5a78963acea2229fd9be5f0e5e0aaa99' }
